### ISSUE TITLE
Incorrect supported platforms

### ISSUE THREAD

**Issue by ekuleshov** [halildurmus/win32#166] opened 2021-03-04 06:00 UTC
It seems like this library does not declare windows-only support.

So, [pub.dev](https://pub.dev/packages/win32) shows Android, iOS, Macos and Linux as supported platforms, but they don't have win32 api.

**Comment by timsneath** [comment] 2021-03-07 02:57
Agree. This is not a bug in win32, though, which does not declare support for these other platforms. 

Tagging @mit-mit, who might have some ideas on where this fits on the pub / pana roadmap.

**Comment by ekuleshov** [comment] 2021-03-07 03:08
@timsneath there is probably several ways to address this. E.g. handle it on pub.dev or somehow declare windows-only support in this library. That's how it is being done for flutter plugins, but this is plain dart.

**Comment by timsneath** [comment] 2021-03-07 04:31
Thanks! To the best of my knowledge, there's no way for pure Dart packages to declare platform support, so the only route that I'm aware of requires work to be done outside of this package.

**Comment by timsneath** [comment] 2021-03-17 04:16
Closing this issue for now, since it will be fixed as/when pub.dev is able to support explicit definition of platform supports.

**Closed as completed by timsneath** 2021-03-17 04:16 UTC
