### ISSUE TITLE
dart crashed when using RegEnumValue too frequently

### ISSUE THREAD

**Issue by FengChendian** [halildurmus/win32#261] opened 2021-06-19 18:11 UTC
If I use RegEnumValue too frequently, dart VM will exited Exited (3221226356) even thought I free all pointer. And because of that, flutter APP will crash too.
Exited Code Like this:
![图片](https://user-images.githubusercontent.com/37545115/122651305-8307d800-d16a-11eb-9040-c0f0f4b1532b.png)

I can't get more information from this code. I found that my app memory increased when I call this function. **Maybe it is memory leakage**. I also try call RegEnumValue using C++, I can exited with 0 successfully. 
Here is my code:
```dart
import 'dart:ffi';

import 'package:ffi/ffi.dart';
import 'package:win32/win32.dart';

List<String> getAvailablePorts() {
  /// availablePorts String list
  List<String> portsList = [];

  final hKeyPtr = calloc<IntPtr>();
  final keyPath = TEXT("HARDWARE\\DEVICEMAP\\SERIALCOMM");
  if (RegOpenKeyEx(HKEY_LOCAL_MACHINE, keyPath, 0, KEY_READ, hKeyPtr) !=
      ERROR_SUCCESS) {
    RegCloseKey(hKeyPtr.value);
    Exception("can't open Register");
    return portsList;
  }

  int status = ERROR_SUCCESS;

  /// The index of the value to be retrieved.
  /// This parameter should be zero for the first call to the RegEnumValue function and then be incremented for subsequent calls.
  int dwIndex = 0;

  /// lpValueName
  /// A pointer to a buffer that receives the name of the value as a null-terminated string.
  /// This buffer must be large enough to include the terminating null character.
  final lpValueName = wsalloc(MAX_PATH);

  /// lpcchValueName
  /// A pointer to a variable that specifies the size of the buffer pointed to by the lpValueName parameter
  final lpcchValueName = calloc<Uint32>();
  lpcchValueName.value = MAX_PATH;

  /// A pointer to a variable that receives a code indicating the type of data stored in the specified value.
  final lpType = calloc<Uint32>();

  /// A pointer to a buffer that receives the data for the value entry.
  /// This parameter can be NULL if the data is not required.
  Pointer<Uint8> lpData = calloc<Uint8>();

  /// lpcbData
  /// A pointer to a variable that specifies the size of the buffer pointed to by the lpData parameter, in bytes.
  /// When the function returns, the variable receives the number of bytes stored in the buffer.
  var lpcbData = calloc<DWORD>();
  lpcbData.value = MAX_PATH;

  while (status != ERROR_NO_MORE_ITEMS) {
    status = RegEnumValue(hKeyPtr.value, dwIndex++, lpValueName, lpcchValueName,
        nullptr, lpType, lpData, lpcbData);

    switch (status) {
      case ERROR_SUCCESS:
        Pointer<Utf8> str = wsalloc(1000).cast();
        WideCharToMultiByte(
            0, 0, lpData.cast(), -1, str, MAX_PATH, nullptr, nullptr);
        // portsList.add(String.fromCharCodes(lpData.asTypedList(8)));
        portsList.add(str.toDartString());
        free(str);
        break;
      case ERROR_MORE_DATA:
        Exception("ERROR_MORE_DATA");
        break;
      default:
        break;
    }
  }
  free(hKeyPtr);
  free(lpValueName);
  free(lpcchValueName);
  free(lpType);
  free(lpData);
  free(lpcbData);
  free(keyPath);

  RegCloseKey(hKeyPtr.value);
  return portsList;
}

main(List<String> args) {
  print(getAvailablePorts());
  print(getAvailablePorts());
  print(getAvailablePorts());
  print(getAvailablePorts());
  print(getAvailablePorts());
  print(getAvailablePorts());
  print(getAvailablePorts());
  print(getAvailablePorts());
  print(getAvailablePorts());
  print(getAvailablePorts());
  print(getAvailablePorts());
  print(getAvailablePorts());
  print(getAvailablePorts());
}

```

**Comment by timsneath** [comment] 2021-06-19 20:30
You have a problem somewhere, but I think it might be due to you reallocating memory. 

I find it helpful to extract API calls into functions, which lets you use a `try` / `finally` pattern and make sure that all memory gets cleaned up successfully. 

I broke your code into a few separate functions, and this seems to run well on my machine, at least to 10,000 invocations:

```dart
import 'dart:ffi';
import 'dart:io';

import 'package:ffi/ffi.dart';
import 'package:win32/win32.dart';

const regKey = r'HARDWARE\DEVICEMAP\KeyboardClass';
const MAX_ITEMLENGTH = 1024;

class RegistryKeyValuePair {
  final String key;
  final String value;

  const RegistryKeyValuePair(this.key, this.value);
}

int getRegistryKeyHandle(String key) {
  final phKey = calloc<HANDLE>();
  final lpKeyPath = key.toNativeUtf16();

  try {
    if (RegOpenKeyEx(HKEY_LOCAL_MACHINE, lpKeyPath, 0, KEY_READ, phKey) !=
        ERROR_SUCCESS) {
      RegCloseKey(phKey.value);
      throw Exception("Can't open registry key");
    }

    return phKey.value;
  } finally {
    free(phKey);
    free(lpKeyPath);
  }
}

RegistryKeyValuePair? enumerateKey(int hKey, int index) {
  final lpValueName = wsalloc(MAX_PATH);
  final lpcchValueName = calloc<DWORD>()..value = MAX_PATH;
  final lpType = calloc<DWORD>();
  final lpData = calloc<BYTE>(MAX_ITEMLENGTH);
  final lpcbData = calloc<DWORD>()..value = MAX_ITEMLENGTH;

  try {
    final status = RegEnumValue(hKey, index, lpValueName, lpcchValueName,
        nullptr, lpType, lpData, lpcbData);

    switch (status) {
      case ERROR_SUCCESS:
        if (lpType.value != REG_SZ) throw Exception('Non-string content.');
        return RegistryKeyValuePair(
            lpValueName.toDartString(), lpData.cast<Utf16>().toDartString());

      case ERROR_MORE_DATA:
        throw Exception('An item required more than $MAX_ITEMLENGTH bytes.');

      case ERROR_NO_MORE_ITEMS:
        return null;

      default:
        throw Exception('unknown error');
    }
  } finally {
    free(lpValueName);
    free(lpcchValueName);
    free(lpType);
    free(lpData);
    free(lpcbData);
  }
}

Map<String, String> getAvailablePorts() {
  /// availablePorts String list
  final portsList = <String, String>{};

  final hKey = getRegistryKeyHandle(regKey);

  /// The index of the value to be retrieved.
  /// This parameter should be zero for the first call to the RegEnumValue function and then be incremented for subsequent calls.
  var dwIndex = 0;
  RegistryKeyValuePair? item;

  item = enumerateKey(hKey, dwIndex);
  while (item != null) {
    portsList[item.key] = item.value;
    dwIndex++;
    item = enumerateKey(hKey, dwIndex);
  }

  RegCloseKey(hKey);
  return portsList;
}

void main(List<String> args) {
  for (var i = 0; i < 10000; i++) {
    final ports = getAvailablePorts();
    if (ports.isEmpty) exit(1);
    stdout.write('.');
  }
  print('\nAll done!');
}
```

A couple of other notes on your code:

- You shouldn't need to use `WideCharToMultiByte`. You're calling the widechar version of the code, so you'll get Unicode strings back. 
- Don't forget to `throw` an `Exception`, not merely call it. 
- I changed the key for my example to `r'HARDWARE\DEVICEMAP\KeyboardClass'`, since my machine doesn't have any serial ports.

Hope this helps!

**Comment by timsneath** [comment] 2021-06-20 01:40
For completeness, I slightly modified my example and added it here: 
https://github.com/timsneath/win32/blob/main/example/registry.dart

Closing this issue for now, but feel free to reopen if you have a reproducible bug against win32. Thanks for using it!

**Closed as completed by timsneath** 2021-06-20 01:40 UTC

**Comment by FengChendian** [comment] 2021-06-20 02:09
Thanks for your example! Your code can run well on my machine. 

And you are right. The problem is due to reallocating memory.
In your code:
```dart
final lpData = calloc<BYTE>(1024);
```
And In my code
```dart
final lpData = calloc<BYTE>();
// or final lpData = calloc<Uint8>();
```
Then if lpData is not NULL, dart will Exited (3221226356) when lpData was called the second time. Maybe it tries to reallocate memory size for existing pointer.

Thanks for your notes. By the way:
- I know that I will get Unicode strings back. I want to get a result like [COM5] natively, but the Unicode strings will give result like [C O M 5]. Maybe I use cast<Utf16>().toDartString() better...
- Yeah, `try` / `throw` / `finally` is a good habit. I forgot it because I often using C language, which doesn't have `try`.😂
