### ISSUE TITLE
Request WbemRefresher to access performance data

### ISSUE THREAD

**Issue by kolyneh** [halildurmus/win32#410] opened 2022-04-20 02:33 UTC
Thanks to your great work!

I want to access performance data as documented here:
[https://docs.microsoft.com/en-us/windows/win32/wmisdk/accessing-performance-data-in-c--](https://github.com/timsneath/win32/issues/url)

Help please!
Thank you!

#408

**Comment by timsneath** [comment] 2022-04-20 05:44
Duplicate of #408

**Closed as completed by timsneath** 2022-04-20 05:44 UTC
